version: '3.9'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./volume-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_PASSWORD}