// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewStudent struct {
	Degree    string `json:"degree"`
	Course    string `json:"course"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	StartedOn string `json:"started_on"`
}

type Query struct {
}

type Student struct {
	ID        string `json:"id"`
	Degree    string `json:"degree"`
	Course    string `json:"course"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	StartedOn string `json:"started_on"`
}
